server:
  port: 8085
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/novel?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 1664125539@qq.com
    # 密码是开启SMTP服务的授权码
    password: xxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
python:
#  exe-file: '/Users/tenghaiyi/PycharmProjects/novel_python/novel.py'
#  target-path: '/Users/novel/'
#  source-py-path: '/Library/Frameworks/Python.framework/Versions/3.10/bin/python3'
  exe-file: 'D:\\project\\thy\\python\\novel\\novel.py'
  target-path: 'G:\\novel\\'
  source-py-path: 'G:\\AppData\\Local\\Programs\\Python\\Python38\\python'