server:
  port: 8085
spring:
  datasource:
    username: root
    password: root123456
    url: jdbc:mysql://127.0.0.1:3306/novel?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 1664125539@qq.com
    # 密码是开启SMTP服务的授权码
    password: xxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
