server:
  port: 11101
spring:
  datasource:
    username: shiny
    password: Shiny0102.
    url: jdbc:mysql://43.138.212.92:3306/novel?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 1664125539@qq.com
    # 密码是开启SMTP服务的授权码
    password: bcmdujodwwlocahf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
python:
  exe-file: '/home/ubuntu/python/novel.py'
  target-path: '/opt/novel/'
